import { type ReactNode } from "react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { ValidationResults } from "./ValidationAdvanced";
import { evaluatePrecision, formatValidationNumber as fmt, type ValidationCheck } from "@/lib/validationAdvanced";
import { parseMeasurements, stats } from "@/lib/validationCalculator";

function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}) {
 return <div className="overflow-x-auto rounded-lg border bg-card shadow-sm"><table className="w-full text-sm"><thead className="bg-muted text-muted-foreground"><tr>{headers.map(h=><th key={h} className="p-3 text-left font-medium">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((r,i)=><tr key={i} className="hover:bg-accent">{r.map((c,j)=><td key={j} className="p-3 tabular-nums">{c}</td>)}</tr>)}</tbody></table></div>;
}
export default function ValidationAccuracyTables({analyte,text,precision,checks,section="all"}:{section?:"all"|"accuracy"|"precision";analyte:string;text:string;precision:ReturnType<typeof evaluatePrecision>;checks:ValidationCheck[]}) {
 const parsed=parseMeasurements(text,3);
 return <div className="space-y-4">
 {section !== "precision" && <Card><CardHeader><CardTitle className="text-base">ตารางที่ 3 ผลการประเมินความถูกต้องและความเที่ยงแบบทำซ้ำของวิธีวิเคราะห์ {analyte}</CardTitle></CardHeader><CardContent className="space-y-3"><Table headers={["Target (mg/mL)","n","Mean Found (mg/mL)","SD Found","Mean Recovery (%)","RSD Recovery (%)","HorRat(r)"]} rows={precision.summaries.map(s=>{const rows=parsed.errors.length?[]:parsed.rows.filter(r=>r[0]===s.level);const found=stats(rows.map(r=>r[2]));return [s.level,rows.length,fmt(found?.mean),fmt(found?.sd),fmt(s.repeatability?.mean),fmt(s.repeatability?.rsd),fmt(s.ratio)];})}/><ValidationResults checks={checks.filter(c=>c.name.startsWith("Recovery ")||c.name.startsWith("Repeatability "))}/></CardContent></Card>}
 {section !== "accuracy" && <Card><CardHeader><CardTitle className="text-base">ตารางที่ 4 ผลการประเมินความเที่ยงระหว่างวันวิเคราะห์ {analyte}</CardTitle></CardHeader><CardContent className="space-y-3"><Table headers={["Target (mg/mL)","วัน","Mean Recovery (%)","SD ภายในวัน","SD ระหว่างวัน","SD รวม","RSD รวม (%)","HorRat(IP)"]} rows={precision.summaries.map(s=>[s.level,s.days.length,fmt(s.anova?.mean),fmt(s.anova?.withinSd),fmt(s.anova?.betweenSd),fmt(s.anova?.sd),fmt(s.anova?.rsd),fmt(s.intermediateRatio)])}/><Table headers={["Target (mg/mL)","วันวิเคราะห์","n","Mean Found (mg/mL)","Mean Recovery (%)","SD Recovery","RSD Recovery (%)"]} rows={precision.summaries.flatMap(s=>s.days.map(day=>{const rows=precision.rawDaily.filter(r=>r[1]===s.level&&r[0]===day);const found=stats(rows.map(r=>r[3]));const recovery=rows.every(r=>r[2]>0)?stats(rows.map(r=>r[3]/r[2]*100)):null;return [s.level,day,rows.length,fmt(found?.mean),fmt(recovery?.mean),fmt(recovery?.sd),fmt(recovery?.rsd)];}))}/><p className="text-sm text-muted-foreground">คำนวณจากผลรายตัวอย่างด้วย ANOVA ไม่ใช้ RSD ของค่าเฉลี่ยรายวันแทนความเที่ยงรวม</p><ValidationResults checks={checks.filter(c=>c.name.startsWith("Intermediate Precision "))}/></CardContent></Card>}
 {section === "all" && <Card><CardHeader><CardTitle className="text-base">ตารางที่ 5 สรุปผลการตรวจสอบความใช้ได้ของวิธีวิเคราะห์ {analyte} และสถานะการยอมรับ</CardTitle></CardHeader><CardContent><ValidationResults checks={checks}/></CardContent></Card>}
 </div>;
}
